Fix metrics being mutated during report
wavefrontHQ/wavefront-sdk-python pull request #88
Opened 2021-11-10 10:53 UTC by michi88

fixes https://github.com/wavefrontHQ/wavefront-sdk-python/issues/87

2021-11-10 14:20 UTC, michi88 commented
Also fixes the build now. Not sure what the intention of the setup.py command was, remove it.

2021-11-10 19:32 UTC, keep94 requested changes
Thank you for making all these changes.

2021-11-10 19:32 UTC, keep94 commented on wavefront_sdk/entities/histogram/histogram_impl.py
> +        for thread_item in self.per_thread_dist.items():
consider using 
```
for _, thread_item in self.per_thread_dist.items():
    centroids.extend(thread_item.centroids_to_list())
```

2021-11-10 19:32 UTC, keep94 commented on wavefront_sdk/common/metrics/registry.py
> +        for key, val in self.metrics.copy().items():
Consider adding a comment explaining why this change is necessary. Just explain that copying the dict here protects from concurrent modification while iterating.

2021-11-20 00:28 UTC, keep94 commented
Michi88, when you have a chance, would you check the box that says allow edits by maintainers?  I have already done the changes I asked for locally.  If you check that box, I can amend and merge your pull request.

2021-11-21 04:15 UTC, michi88 commented
@keep94 done!

2021-11-22 19:22 UTC, keep94 commented on wavefront_sdk/common/metrics/registry.py
> +        for key, val in self.metrics.copy().items():
Done.

2021-11-22 19:22 UTC, keep94 commented on wavefront_sdk/entities/histogram/histogram_impl.py
> +        for thread_item in self.per_thread_dist.items():
Done. Used digest instead of thread item as the variable name.

2021-11-22 19:23 UTC, keep94 approved these changes

2021-11-22 19:24 UTC, merged

2021-11-22 23:41 UTC, keep94 commented
michi88,
Thank you for contributing to our project and fixing our build.

2021-11-22 23:55 UTC, ustinov requested changes

2021-11-22 23:55 UTC, ustinov commented on .travis.yml
> -  - if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
@michi88 @keep94 folks please bring back the check, is was making sure the version in setup.py is incremented as needed in every PR that's being merged

2021-11-23 00:07 UTC, ustinov commented on wavefront_sdk/entities/histogram/histogram_impl.py
> +        for _, digest in self.per_thread_dist.items():
Please consider using the `.values()` view instead of `.items()` if you don't use keys